spring :
  datasource :
    url : jdbc:mysql://localhost:3306/yz?useUnicode=true&amp;characterEncoding=UTF-8&allowMultiQueries=true&useAffectedRows=true&useSSL=false
    username : root
    password : 123456
    driverClassName : com.mysql.jdbc.Driver
    platform: mysql
    schema: classpath:/yz.sql
    #第一次启动做建表用，之后注释掉
    #initialization-mode: always
  jackson:
    data-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: readme.md

# JWT
jwt:
  header: Authorization
  secret: mySecret
  #token有效期一天
  expiration: 864000
  tokenHead: "Bearer "
sm:
  connection:
    initialSize: 2
    minIdle: 10
    maxActive: 20
    maxWait: 60000
    maxPoolPreparedStatementPerConnectionSize: 50

